### ISSUE TITLE
Where is the README.md

### ISSUE THREAD

**Issue by a4amado** [IbrahimShaheen103/Face-Api-Js#1]
Dude where is the README.md, I'm not an AI model to figure how this thing works on my own

**Comment by IbrahimShaheen103** [comment]
It's my fault, but my AI model is not trained to remember everything 😀. 
so my friend you can do this steps 

1. git clone https://github.com/IbrahimShaheen103/Face-Api-Js.git
2. open Face-Api-Js Folder 
3. double click on index file and it will run
